FORMAT: 1A
HOST: http://www.google.com

# API

# Group Allelematrix

## MarkerProfile allelematrix [/brapi/allelematrix?markerprofileId=100&markerprofileId=101]
This uses a more efficient data structure and pagination for large number of markers.

### scores [GET]

Use GET when paramater size less than 2K

|Variable|Datatype|Description|Required|  
|-----------|------|------|:-----:|
|markerprofileId|string, list|eg: markerprofileId=100&markerprofileId=101|required
|page|integer||optional
|pageSize|integer||optional

+ Paramaters
    + markerprofileId
    + page
    + pageSize 
+ Response 200 (application/json)

        {
            "metadata"  :   
            {   
                "status"        :   [ ],
                "pagination"    :
                {
                    "pageSize": 100,
                    "currentPage": 1,
                    "totalCount": 1,
                    "totalPages": 1
                }
            },
            "makerprofileIds": ["markerprofileId1","markerprofileId2","markerprofileId3"..]
            },
            "scores": { 
                    "markerId1":["AB","AA","AA"],
                    "markerId2":["AA","AB","AA"],
                    "markerId3":["AB","AB","BB"]
            }
        }

### scores [POST]
Use POST when paramater size greater than 2K
+ Paramaters
    + id (required, string, "100, 101, 103") marker profile id
    + page (optional, integer)
    + pageSize (optional, integer)
+ Response 200 (application/json)

        [
            {"makerprofileIds": ["id1","id2","id3"..]
            },
            "scores": 
                [
                    {"marker1":["AB","AA","AA"]},
                    {"marker2":["AA","AB","AA"]}
                ]
            }
        ]
# Group Field Layout
Field Layout and experiment design **Field Layout API**

## Experiment Design [/brapi/design/list]
Get list of experiments

### List of experiments [GET]

+ Response 200 (application/json)

## Experiment Design [/brapi/design/{id}]
Select experiment for download

### Design for experiment [GET]
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the experiment.
+ Response 200 (application/json)

        [{
          "id": 1, "experiment uid": "experiment name"
        }, {
          "id": 2, "file": "csv file of field layout"
        }]

## Traits [/brapi/traits/list]
Get list of traits

### List of traits [GET]

+ Response 200 (application/json)

## Traits [/brapi/traits/get/{id}]
Select from traits for download.

+ Parameters
    + id (required, array, `[1],[2]`) ... array containing `id` of the Traits

### Retrieve traits [GET]
+ Response 200 (application/json)

        "file": "csv file of trait definitions"
        
## Traits [/brapi/traits/post/file]
Trait definitions

+ Parameters
    + file (required, file, ``) ... file containing new trait definitions

### Create a trait [POST]

+ Response 200



